"""
Django settings for Maddi project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

import os

# file upload
MEDIA_URL  = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# logging
LOGGING = {
    "version" : 1.0,
    "disable_existing_loggers" : False,
    "formatters" : {
        "format1" : {
            "format" : "[%(asctime)s] [%(levelname)s] [%(name)s : %(lineno)s] %(message)s",
            "datefmt" : "%Y-%m-%d %H:%M:%S",
            },
        "format2" : {
            "format" : "[%(asctime)s] [%(name)s : %(funcName)s : %(lineno)s] %(message)s",
            }
        },
    "handlers" : {
        "file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join(BASE_DIR, "log/logfile.log"),
            "encoding" : "utf-8",
            "maxBytes" : 1024*1024*5,
            "backupCount" : 5,
            "formatter" : "format1"
            },
        "console" : {
            "level" : "DEBUG",
            "class" : "logging.StreamHandler",
            "formatter" : "format2"
            }
        },
    "loggers" : {
        "django" : {
            "handlers" : ["file"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "django.server" : {
            "handlers" : ["file"],
            "propagate" : False,
            "level" : "DEBUG"
            },
        "django.request" : {
            "handlers" : ["file"],
            "propagate" : False,
            "level" : "DEBUG"
            },
        "md_admin" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_combi" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_favorite" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_main" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_member" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_order" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_recommend" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_review" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        "md_store" : {
            "handlers" : ["file", "console"],
            # "propagate" : True,
            "level" : "DEBUG"
            },
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sr)kmk93#xfgkg*qe8)sfqfnv_dg2f_*00r_k0m7(1!bp&!xr_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     '192.168.0.2',
#     '192.168.0.119',
#     '192.168.0.16',
#     '192.168.0.85',
#     ]
ALLOWED_HOSTS = [
    '*'
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'mathfilters',
    'md_admin.apps.MdAdminConfig',
    'md_combi.apps.MdCombiConfig',
    'md_favorite.apps.MdFavoriteConfig',
    'md_main.apps.MdMainConfig',
    'md_member.apps.MdMemberConfig',
    'md_order.apps.MdOrderConfig',
    'md_recommend.apps.MdRecommendConfig',
    'md_review.apps.MdReviewConfig',
    'md_store.apps.MdStoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.0.86:8000',
    'http://t1.daumcdn.net',
    'http://dapi.kakao.com',
    'http://map.daumcdn.net',
]

CORS_ORIGIN_ALLOW_ALL  = True  
CORS_ALLOW_CREDENTIALS = True

# kakao maps api
# - error message : The Cross Origin Opener Policy header has been ignored
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'


ROOT_URLCONF = 'Maddi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Maddi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

##########
# sqlite3
##########
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

##########
# mysql
##########
DATABASES = {
    'default': {
        'ENGINE'    : 'django.db.backends.mysql',
        'NAME'      : 'bit',                  # database name
        'USER'      : 'bit',
        'PASSWORD'  : 'bit',
        'HOST'      : '218.153.113.20',       # ip
        # 'HOST'      : '127.0.0.1',       # ip
        'PORT'      : '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
